// FOR PHONE LOGIN
export const PHONE_LOGIN_REQUEST = "PHONE_LOGIN_REQUEST"
export const PHONE_LOGIN_SUCCESS = "PHONE_LOGIN_SUCCESS"
export const PHONE_LOGIN_FAILURE = "PHONE_LOGIN_FAILURE"
// FOR GOOGLE LOGIN
export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST"
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS"
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE"
// FOR OTP VERIFY
export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST"
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS"
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE"
