import {
  PHONE_LOGIN_REQUEST,
  PHONE_LOGIN_SUCCESS,
  PHONE_LOGIN_FAILURE,
  GOOGLE_LOGIN_REQUEST,
  GOOGLE_LOGIN_SUCCESS,
  GOOGLE_LOGIN_FAILURE,
  OTP_VERIFY_FAILURE,
  OTP_VERIFY_REQUEST,
  OTP_VERIFY_SUCCESS,
} from "./ActionType";
export const phoneLoginRequest = (phoneno) => ({
    type : PHONE_LOGIN_REQUEST,
    phoneno 

})