// FOR PHONE LOGIN
export const PHONE_LOGIN_REQUEST = "PHONE_LOGIN_REQUEST"
export const PHONE_LOGIN_SUCCESS = "PHONE_LOGIN_SUCCESS"
export const PHONE_LOGIN_FAILURE = "PHONE_LOGIN_FAILURE"
// FOR GOOGLE LOGIN
export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST"
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS"
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE"
// FOR OTP VERIFY
export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST"
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS"
export const OTP_VERIFY_FAILURE = "OTP_VERIFY_FAILURE"

export const SEND_OTP_REQUEST ="SEND_OTP_REQUEST"

export const VERIFY_OTP_REQUEST ="VERIFY_OTP_REQUEST"
export const SEND_OTP_SUCCESS='SEND_OTP_SUCCESS'
export const SEND_OTP_FAILURE= 'SEND_OTP_FAILURE'
export const VERIFY_OTP_SUCCESS= 'VERIFY_OTP_SUCCESS'

export const VERIFY_OTP_FAILURE="VERIFY_OTP_FAILURE"
export const PROFILE_CREATION_SUCCESS='PROFILE_CREATION_SUCCESS'
export  const PROFILE_CREATION_FAILURE = "PROFILE_CREATION_FAILURE"


export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

