// FOR PHONE LOGIN
export const PHONE_LOGIN_REQUEST = "PHONE_LOGIN_REQUEST";
export const PHONE_LOGIN_SUCCESS = "PHONE_LOGIN_SUCCESS";
export const PHONE_LOGIN_FAILURE = "PHONE_LOGIN_FAILURE";
// FOR GOOGLE LOGIN
export const GOOGLE_LOGIN_REQUEST = "GOOGLE_LOGIN_REQUEST";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE";


export const SEND_OTP_REQUEST = "SEND_OTP_REQUEST";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const SEND_OTP_FAILURE = "SEND_OTP_FAILURE";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAILURE = "CREATE_PROFILE_FAILURE";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";



export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const FETCH_BRAND_REQUEST = "FETCH_BRAND_REQUEST";
export const FETCH_BRAND_SUCCESS = "FETCH_BRAND_SUCCESS";
export const FETCH_BRAND_FAILURE = "FETCH_BRAND_FAILURE";


export const FETCH_SIZES_REQUEST = 'FETCH_SIZES_REQUEST';
export const FETCH_SIZES_SUCCESS = 'FETCH_SIZES_SUCCESS';
export const FETCH_SIZES_FAILURE = 'FETCH_SIZES_FAILURE';

export const FETCH_RELEASE_YEARS_REQUEST = 'FETCH_RELEASE_YEARS_REQUEST';
export const FETCH_RELEASE_YEARS_SUCCESS = 'FETCH_RELEASE_YEARS_SUCCESS';
export const FETCH_RELEASE_YEARS_FAILURE = 'FETCH_RELEASE_YEARS_FAILURE';

export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAILURE = "SEARCH_PRODUCT_FAILURE";
