import Color from "./Color";
import { RFValue } from "react-native-responsive-fontsize";

export default {
  CONTAINER: {
    backgroundColor: Color.BLACK_COLOR,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  SPLASH_LOGO: { height: 250, width: 250 },
  SPLASH_TEXT: {
    color: Color.WHITE_COLOR,
    fontSize: 50,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  ONBOARDSCREEN_TEXT0: {
    color: Color.BLACK_COLOR,
    fontSize: 50,
    fontWeight: "bold",
    letterSpacing: 1,
  },
  ONBOARDSCREEN_TEXT1: {
    color: Color.BLACK_COLOR,
    fontSize: 18,
    fontWeight: "600",
  },
  ONBOARDSCREEN_TEXT4: {
    color: Color.WHITE_COLOR,
    fontSize: RFValue(15),
    marginTop:RFValue(18),
    backgroundColor: Color.BLACK_COLOR,
    width: "100%",
    height: RFValue(45),
    paddingLeft:RFValue(10),
    borderWidth: 1,
    borderColor: Color.WHITE_COLOR,
  },
  ONBOARDSCREEN_TEXT5: {
    color: Color.WHITE_COLOR,
    fontSize: RFValue(15),
    marginTop:RFValue(37),  
    backgroundColor: Color.BLACK_COLOR,
    width: "70%",
    height: RFValue(40),
    paddingLeft:RFValue(8),
    borderWidth: 1,
    borderColor: Color.WHITE_COLOR,
  },

  ONBOARDSCREEN_TEXTFIELD1: {
    backgroundColor: Color.BUTTON_COLOR,
    width: "85%",
    height: 45,
    marginTop: 40,
    marginHorizontal: 20,
    borderRadius: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  ONBOARDSCREEN_TEXTFIELD2: {
    backgroundColor: Color.WHITE_COLOR,
    width: "85%",
    height: 45,
    marginTop: 20,
    marginHorizontal: 20,
    borderRadius: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  ONBOARDSCREEN_TEXTFIELD3: {
    backgroundColor: Color.BUTTON_COLOR,
    width: "100%",
    marginHorizontal: 0,
    height: 45,
    marginTop: 20,
    borderRadius: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  ONBOARDSCREEN_TEXTFIELD4: {
    backgroundColor: Color.BLACK_COLOR,
    width: "100%",
    height: 40,
    marginTop: 22,
    borderRadius: 3,
    justifyContent: "center",
    borderWidth: 2,
    borderColor: Color.WHITE_COLOR,
  },
  ONBOARDSCREEN_TEXTFIELD5: {
    backgroundColor: Color.BUTTON_COLOR,
    width: "23%",
    height: 45,
    marginHorizontal: 20,
    borderRadius: 3,
    justifyContent: "center",
    alignItems: "center",
  },
  modal_back_img: {
    height: RFValue(18),
    width: RFValue(18),
    alignSelf: "flex-start",
  },
  modalText: {
    fontSize: RFValue(18),
    fontWeight: "500",
    marginTop: RFValue(15),
    color: Color.WHITE_COLOR,
    textAlign: "center",
  },
  modalText1: {
    fontSize: RFValue(15),
    marginTop: RFValue(8),
    textAlign: "center",
    color: Color.WHITE_COLOR,
  },
  Number_TextField:{
    flexDirection:'row',
    gap : 2,

  }
};
